server:
  port: 8123
  servlet:
    context-path: /api
spring:
  config:
    name: cloud-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:aws://localhost:3306
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 逻辑删除配置
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: cloud-picture-backend 官方文档
    description: "`配置文件`,**knife4j**"
    version: 1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.lloop.cloudpicturebackend.controller